FROM python:3.6.1-alpine

RUN apk --no-cache add \
    bash \
    unzip \
    curl

ENV TERRAFORM_VERSION=0.11.11

COPY ./tf_install_alpine.sh /root/tf_install_alpine.sh

RUN /root/tf_install_alpine.sh -i ${TERRAFORM_VERSION}

RUN pip install --upgrade pip
RUN pip install awscli chalice

ENTRYPOINT sh
