FROM frolvlad/alpine-python3

RUN apk --no-cache add \
    bash \
    unzip \
    curl


RUN pip install awscli

ARG TERRAFORM_VERSION
ENV TERRAFORM_VERSION=$TERRAFORM_VERSION

COPY ./tf_install_alpine.sh /root/tf_install_alpine.sh

RUN /root/tf_install_alpine.sh -i ${TERRAFORM_VERSION}

RUN pip install --upgrade pip
RUN pip install awscli

ENTRYPOINT sh
