name: docker-ci

on:
  push:

env:
  DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
  TERRAFORM_VERSION: 0.12.24
  DOCKER_VERSION: 19.03.8
  DOCKER_COMPOSE_VERSION: 1.25.4
  VERSION: latest
  KF_VERSION: v1.0.2


jobs:
  base-python-aws:

    name: base-python-aws
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: base-python-aws
    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          fetch-depth: 1

      - name: Build
        run: |
          docker build -t docker.pkg.github.com/carlomazzaferro/docker-ci/$IMAGE_NAME:$VERSION \
                       -f ./generic/Dockerfile.base-python \
                       --build-arg TERRAFORM_VERSION=$TERRAFORM_VERSION \
                       ./generic

          docker tag docker.pkg.github.com/carlomazzaferro/docker-ci/$IMAGE_NAME:$VERSION carlomazzaferro/$IMAGE_NAME:$VERSION

      - name: Push to Dockerhub
        run: |
          echo $DOCKERHUB_TOKEN | docker login -u carlomazzaferro --password-stdin
          docker push carlomazzaferro/$IMAGE_NAME:$VERSION

  alpine-python-terraform-aws:
    name: alpine-python-terraform-aws
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: alpine-python-terraform-aws
    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          fetch-depth: 1

      - name: Build
        run: |
          docker build -t docker.pkg.github.com/carlomazzaferro/docker-ci/$IMAGE_NAME:$VERSION \
                       -f ./concourse/Dockerfile.concourse.alpine.python \
                       --build-arg TERRAFORM_VERSION=$TERRAFORM_VERSION \
                       ./concourse
          docker tag docker.pkg.github.com/carlomazzaferro/docker-ci/$IMAGE_NAME:$VERSION carlomazzaferro/$IMAGE_NAME:$VERSION

      - name: Push to Dockerhub
        run: |
          echo $DOCKERHUB_TOKEN | docker login -u carlomazzaferro --password-stdin
          docker push carlomazzaferro/$IMAGE_NAME:$VERSION

  alpine-python-terraform-aws-dind:
    name: alpine-python-terraform-aws-dind
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: alpine-python-terraform-aws-dind
    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          fetch-depth: 1

      - name: Build
        run: |
          docker build -t docker.pkg.github.com/carlomazzaferro/docker-ci/$IMAGE_NAME:$VERSION \
                       -f ./concourse/Dockerfile.concourse.dind.awscli \
                       --build-arg TERRAFORM_VERSION=$TERRAFORM_VERSION \
                       --build-arg DOCKER_COMPOSE_VERSION=$DOCKER_COMPOSE_VERSION \
                       ./concourse/
          docker tag docker.pkg.github.com/carlomazzaferro/docker-ci/$IMAGE_NAME:$VERSION carlomazzaferro/$IMAGE_NAME:$VERSION

      - name: Push to Dockerhub
        run: |
          echo $DOCKERHUB_TOKEN | docker login -u carlomazzaferro --password-stdin
          docker push carlomazzaferro/$IMAGE_NAME:$VERSION

  alpine-python-terraform-aws-kubectl:
    name: alpine-python-terraform-aws-kubectl
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: alpine-python-terraform-aws-kubectl
    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          fetch-depth: 1

      - name: Build
        run: |
          docker build --build-arg KF_VERSION=$KF_VERSION \
                       -t docker.pkg.github.com/carlomazzaferro/docker-ci/$IMAGE_NAME:$VERSION \
                       -f ./k8s/Dockerfile.alpine.tf.aws.kubectl \
                       ./k8s

          docker tag docker.pkg.github.com/carlomazzaferro/docker-ci/$IMAGE_NAME:$VERSION carlomazzaferro/$IMAGE_NAME:$VERSION

      - name: Push to Dockerhub
        run: |
          echo $DOCKERHUB_TOKEN | docker login -u carlomazzaferro --password-stdin
          docker push carlomazzaferro/$IMAGE_NAME:$VERSION


  buildpack-terraform:
    name: buildpack-terraform
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: buildpack-terraform
    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          fetch-depth: 1

      - name: Build
        run: |
          docker build -t docker.pkg.github.com/carlomazzaferro/docker-ci/$IMAGE_NAME:$VERSION \
                       --build-arg TERRAFORM_VERSION=$TERRAFORM_VERSION \
                       -f ./generic/Dockerfile.buildpack.terraform \
                       ./generic

          docker tag docker.pkg.github.com/carlomazzaferro/docker-ci/$IMAGE_NAME:$VERSION carlomazzaferro/$IMAGE_NAME:$VERSION

      - name: Push to Dockerhub
        run: |
          echo $DOCKERHUB_TOKEN | docker login -u carlomazzaferro --password-stdin
          docker push carlomazzaferro/$IMAGE_NAME:$VERSION

  circle-ci-terraform-awscli:
    name: circle-ci-terraform-awscli
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: circle-ci-terraform-awscli
    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          fetch-depth: 1

      - name: Build
        run: |
          docker build -t docker.pkg.github.com/carlomazzaferro/docker-ci/$IMAGE_NAME:$VERSION \
                       -f ./circleci/Dockerfile.circle.terraform.awscli \
                       --build-arg TERRAFORM_VERSION=$TERRAFORM_VERSION \
                       ./circleci

          docker tag docker.pkg.github.com/carlomazzaferro/docker-ci/$IMAGE_NAME:$VERSION carlomazzaferro/$IMAGE_NAME:$VERSION

      - name: Push to Dockerhub
        run: |
          echo $DOCKERHUB_TOKEN | docker login -u carlomazzaferro --password-stdin
          docker push carlomazzaferro/$IMAGE_NAME:$VERSION



